### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The initial icon I made is pretty shit, looking into it in retrospect. I made this one which is far more simplistic but can get the point across. If you approve of this, I'll go ahead with it and pixel fit these.

### CODE REVIEW

**Comment by phase1geo** [comment]
Could you try a couple of variations by incorporating the brand color? I’d like to see what that would look like. I do like the direction this is taking though.

**Comment by phase1geo** [comment]
The brand color is D48E15

**Comment by Fatih20** [comment]
I'll look into it.

**Comment by Fatih20** [comment]
I've tried it. It feels forced and contrived.

I don't see why it should, Minder doesn't have purple on its icon.

**Comment by phase1geo** [comment]
Correct, but Minder’s icon does contain some color. The color would not necessarily have to be the brand color, but I was curious to see what it would look like.

**Comment by Fatih20** [comment]
It's kinda fitting and on-theme with Minder. I still have affinity for the previous one.
image

**Comment by phase1geo** [comment]
I’m not a fan of this color scheme for Outliner. Could we try a version where the background color is the solarized light background theme color? The foreground elements of the icon should be all the same color or the lines should be of one color while the shapes would be a single different color.

**Comment by phase1geo** [comment]
The solarized light color is FDF6E3.

**Comment by Fatih20** [comment]
image
I thnk the one where the shape and the line has different color with the shape having darker color makes much more sense.

**Comment by phase1geo** [comment]
I like the look of this one.

**Comment by Fatih20** [comment]
I'll move forward with it.

**Comment by Fatih20** [comment]
Download, compile, and check it out for yourselves before merging this.

**Comment by phase1geo** [comment]
Will do.

**Comment by phase1geo** [comment]
I think most of the icons look pretty good. I'm thinking that the 16 px version should probably remove one of the rows and respace the remaining two to help make it look a bit better. All of the other sizes look good, in my opinion. If you would be willing to regenerate the 16 px version, I think I'm ready to merge the changes.

I really appreciate your help in all of the iconography that you have made for me and other elementary projects!

**Comment by Fatih20** [comment]
I'll get on it.
Sure, buddy!

**Comment by Fatih20** [comment]
Don't forget to credit me!

**Comment by phase1geo** [comment]
Of course!

**Comment by Fatih20** [comment]
Here's a video showing me making this icon in case you're interested.
https://open.lbry.com/@Fatih109:4/Outliner:b?r=Cg1pp5MCWV1a5Nj5jDumPs9b13dNZqWG

**Comment by phase1geo** [comment]
That’s really cool. Thanks for doing this!

**Comment by Fatih20** [comment]
> That’s really cool. Thanks for doing this!

If you don't mind, can you link the video alongside my credit in the release notes? Thanks in advance.

**Comment by phase1geo** [comment]
I can put the URL in the release notes; however, the link won’t be clickable link in the release notes because those are not supported in the syntax. Would you like me to add it to the README.md file as well? That would allow people on GitHub to click on the video.

**Comment by Fatih20** [comment]
> I can put the URL in the release notes; however, the link won’t be clickable link in the release notes because those are not supported in the syntax. Would you like me to add it to the README.md file as well? That would allow people on GitHub to click on the video.

Sure, thanks!

**Pull request merged**
